version: '3.8'
services:
  app:
    build:
      context: .
      args:        
        ENV: Development # O puedes cambiarlo a Production/Staging según sea necesario
    ports:
      - "5000:5000" # Asegúrate de que el puerto de exposición coincida con ASPNETCORE_URLS
    depends_on:
      - db
    environment:
      - ASPNETCORE_ENVIRONMENT=Development # O Production/Staging según sea necesario
      - ConnectionStrings__postgrestDB=Host=db;Port=5432;Database=postgres;Username=postgres;Password=postgres;Timeout=30
    volumes:
      - ./Configuration:/app/Configuration # Solo si necesitas editar los archivos de configuración sin reconstruir el contenedor

  db:
    image: postgres:latest # Especifica una versión para evitar problemas de compatibilidad inesperados
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432" # Opcional: Exponer el puerto solo si necesitas acceder a la DB desde fuera de Docker
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
