version: '3.8'
services:
  app:
    build: .
    ports:
      - "5000:80"
    depends_on:
      - db
    environment:
      ConnectionStrings__postgrestDB: "Host=db;Port=5432;Database=postgres;Username=postgres;Password=postgres;Timeout=30"

  db:
    image: postgres
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
