version: '3.8'
services:
  app:
    build:
      context: .
      args:      
        ENV: Development
    ports:
      - "5000:5131"
    depends_on:
      - db
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__postgrestDB=Host=db;Port=5432;Database=postgres;Username=postgres;Password=postgres;Timeout=30
    volumes:
      - ./Configuration:/app/Configuration

  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./postgres-init/:/docker-entrypoint-initdb.d/

volumes:
  postgres-data:
